/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions
*/

select *
from start_version_update('1.4', 'Added missing function for getting translations from database',
                          _component := 'languages_translations');

create or replace function public.export_translations(_data_group text)
	returns table
	        (
		        __lang_code    text,
		        __translations json,
		        __count        bigint
	        )
	stable
	language sql
as
$$
select language_code
		 , json_object_agg(data_object_code, value)
		 , count(translation_id)
from translation
where data_group = _data_group
group by language_code
$$;

select *
from stop_version_update('1.4', _component := 'languages_translations');